movie/MovieCoreMvcUI/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Net.Http;
using System.Text.Json.Serialization;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using movieentity1;
using System.Security.Cryptography.X509Certificates;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MovieCoreMvcUI.Controllers
{
    public class MovieController : Controller
    {
        private IConfiguration _configuration;
        public MovieController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IEnumerable<MovieEL> movieresult= null;
            using (HttpClient client = new HttpClient())
            {
                string endpoint = _configuration["WebApiBaseUrl"] + "Movie/GetMovies";
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result=await response.Content.ReadAsStringAsync();
                        movieresult=JsonConvert.DeserializeObject<IEnumerable<MovieEL>>(result);    
                    }
                }
            }
                return View(movieresult);
        }

        public async Task<IActionResult> EditMovie(int Id)
        {
            MovieEL movieel = null;
            using (HttpClient client = new HttpClient())
            {
                string endpoint = _configuration["WebApiBaseUrl"] + "Movie/GetMovieById?movieId="+Id;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        movieel = JsonConvert.DeserializeObject<MovieEL>(result);
                    }
                }
            }
            return View(movieel);

        }
        

        [HttpPost]
        public async Task<IActionResult> EditMovie(MovieEL movie)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(movie), Encoding.UTF8, "application/json");
                string endpoint = _configuration["WebApiBaseUrl"] + "Movie/UpdateMovie";
                using (var response = await client.PutAsync(endpoint,content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Movie details updated successfully";

                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "wrong entity";
                    }
                }
            }
            return View();
        }
        public async Task<IActionResult> DeleteMovie(int Id)
        {
            MovieEL movieel = null;
            using (HttpClient client = new HttpClient())
            {
                string endpoint = _configuration["WebApiBaseUrl"] + "Movie/GetMovieById?movieId=" + Id;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        movieel = JsonConvert.DeserializeObject<MovieEL>(result);
                    }
                }
            }
            return View(movieel);

        }
        [HttpPost]
        public async Task<IActionResult> DeleteMovie(MovieEL movieEL)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                string endpoint = _configuration["WebApiBaseUrl"] + "Movie/DeleteMovie?movieId=" +movieEL.Id;
                using (var response = await client.DeleteAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Movie details deleted successfully";

                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "wrong entity";
                    }
                }
            }
            return View();
        }
        public IActionResult MovieEntry()
        {
            //List<SelectListItem> language = new List<SelectListItem>()
            //{
            //    new SelectListItem{Value="Select",Text="select"},
            //    new SelectListItem{Value="Tamil",Text="Tamil"},
            //    new SelectListItem{Value="English",Text="English"},
            //    new SelectListItem{Value="Kannada",Text="Kannada"},
            //};
            //ViewBag.languagelist = language;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> MovieEntry(MovieEL movie)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(movie), Encoding.UTF8, "application/json");
                string endpoint = _configuration["WebApiBaseUrl"] + "Movie/AddMovie";
                using (var response = await client.PostAsync(endpoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Movie details saved successfully";

                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "wrong entity";
                    }
                }
            }
            return View();
        }

       

    }
}

movie/MovieCoreMvcUI/Controllers/TheatreController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using movieentity1;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MovieCoreMvcUI.Controllers
{
    public class TheatreController : Controller
    {
        private IConfiguration _configuration;
        public TheatreController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IEnumerable<Theatre> movieresult = null;
            using (HttpClient client = new HttpClient())
            {
                string endpoint = _configuration["WebApiBaseUrl"] + "Theatre/GetTheatres";
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        movieresult = JsonConvert.DeserializeObject<IEnumerable<Theatre>>(result);
                    }
                }
            }
            return View(movieresult);
        }
        public async Task<IActionResult> EditTheatre(int Id)
        {
            Theatre movieel = null;
            using (HttpClient client = new HttpClient())
            {
                string endpoint = _configuration["WebApiBaseUrl"] + "Theatre/GetTheatreById?TheatreId=" + Id;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        movieel = JsonConvert.DeserializeObject<Theatre>(result);
                    }
                }
            }
            return View(movieel);

        }


        [HttpPost]
        public async Task<IActionResult> EditTheatre(Theatre movie)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(movie), Encoding.UTF8, "application/json");
                string endpoint = _configuration["WebApiBaseUrl"] + "Theatre/UpdateTheatre";
                using (var response = await client.PutAsync(endpoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Theatre details updated successfully";

                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "wrong entity";
                    }
                }
            }
            return View();
        }
        public async Task<IActionResult> DeleteTheatre(int Id)
        {
            MovieEL movieel = null;
            using (HttpClient client = new HttpClient())
            {
                string endpoint = _configuration["WebApiBaseUrl"] + "Theatre/GetTheatreById?TheatreId=" + Id;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        movieel = JsonConvert.DeserializeObject<MovieEL>(result);
                    }
                }
            }
            return View(movieel);

        }
        [HttpPost]
        public async Task<IActionResult> DeleteTheatre(Theatre movieEL)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                string endpoint = _configuration["WebApiBaseUrl"] + "Theatre/DeleteTheatre?TheatreId=" + movieEL.Id;
                using (var response = await client.DeleteAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Theatre details deleted successfully";

                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "wrong entity";
                    }
                }
            }
            return View();
        }
        public IActionResult TheatreEntry()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> TheatreEntry(Theatre theatre)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(theatre), Encoding.UTF8, "application/json");
                string endpoint = _configuration["WebApiBaseUrl"] + "Theatre/AddTheatre";
                using (var response = await client.PostAsync(endpoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "theatre details saved successfully";

                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "wrong entity";
                    }
                }
            }
            return View();
        }
    }
}

movie/MovieCoreMvcUI/Views/Theatre/DeleteTheatre.cshtml
@model movieentity1.Theatre
@*@{
    ViewData["Title"] = "DeleteTheatre";
}*@

<h1>Delete Theatre</h1>
<hr />
<form method="post" enctype="multipart/form-data">
    <div class=" =form-group">
        <label>Id</label>
        <input type="text" asp-for="Id" class="form-control" placeholder="enter theatre id" required />
    </div>
    <input type="submit" value="Save" class="btn btn-outline-success" />
    <input type="button" value="Reset" class="btn btn-outline-secondary" />
    <hr />
</form>
@if (ViewBag.status == "Ok")
{
    <div class="alert alert-success">
        @ViewBag.message
    </div>
}
else if (ViewBag.status == "Error")
{
    <div class="alert alert-danger">
        @ViewBag.message
    </div>
}

movie/MovieCoreMvcUI/Views/Theatre/EditTheatre.cshtml
@model movieentity1.Theatre
@{
    ViewData["Title"] = "EditTheatre";
}

<h1>EditTheatre</h1>
<hr />
<form method="post" enctype="multipart/form-data">
    <h2>Theatre Entry</h2><hr />
    <div class=" =form-group">
        <label>Id</label>
        <input type="text" asp-for="Id" class="form-control" placeholder="enter theatre id" required />
    </div>
    <div class=" =form-group">
        <label>address</label>
        <input type="text" asp-for="Address" class="form-control" placeholder="enter theatre address" required />
    </div>
    <div class=" =form-group">
        <label>theatre name</label>
        <input type="text" asp-for="Name" class="form-control" placeholder="enter theatre name" required />
    </div>
    <div class=" =form-group">
        <label>comments</label>
        <input type="text" asp-for="Comments" class="form-control" placeholder="enter theatre reviews" required />
    </div>

    <input type="submit" value="Save" class="btn btn-outline-success" />
    <input type="button" value="Reset" class="btn btn-outline-secondary" />
    <hr />
</form>
@if (ViewBag.status == "Ok")
{
    <div class="alert alert-success">
        @ViewBag.message
    </div>

}
else if (ViewBag.status == "Error")
{
    <div class="alert alert-danger">
        @ViewBag.message
    </div>
}

movie/MovieCoreMvcUI/Views/Theatre/Index.cshtml
@model IEnumerable<movieentity1.Theatre>
<div>
    <hr />
    <a asp-controller="Theatre" asp-action="TheatreEntry">
        Theatre entry
    </a><hr />
</div>
<div class=" row">
    <div class="col-12">
        <h3>theatre</h3>
        <hr />
        <table class="table table-light table-bordered table-hover">
            <thead>
                <tr>
                    <th>theatre id</th>
                    <th>Name</th>
                    <th>theatre address</th>
                    <th>review</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var movie in Model)
                {
                    <tr>
                        <td>@movie.Id</td>
                        <td>@movie.Name</td>
                        <td>@movie.Address</td>
                        <td>@movie.Comments</td>
                        <td>
                            <a asp-controller="Theatre" asp-action="EditTheatre"
                           asp-route-Id="@movie.Id">Edit</a>
                        </td>
                        <td>
                            <a asp-controller="Theatre" asp-action="DeleteTheatre"
                           asp-route-Id="@movie.Id">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

movie/MovieCoreMvcUI/Views/Theatre/TheatreEntry.cshtml
@{
    ViewData["Title"] = "TheatreEntry";
}
@model movieentity1.Theatre;
<div>
    <hr />
    <a asp-controller="Movie" asp-action="Index">
        Index
    </a><hr />

</div>
<form method="post" enctype="multipart/form-data">
    <h2>Theatre Entry</h2><hr />
    <div class=" =form-group">
        <label>Theatre Name</label>
        <input type="text" asp-for="Name" class="form-control" placeholder="enter theatre name" required />
    </div>
    <div class=" =form-group">
        <label>reviews </label>
        <input type="text" asp-for="Comments" class="form-control" placeholder="enter theatre Comments" required />
    </div>
    <div class=" =form-group">
        <label>Theatre address</label>
        <input type="text" asp-for="Address" class="form-control" placeholder="enter theatre address" required />
    </div>

    <input type="submit" value="Save" class="btn btn-outline-success" />
    <input type="button" value="Reset" class="btn btn-outline-secondary" />
    <hr />
</form>
@if (ViewBag.status == "Ok")
{
    <div class="alert alert-success">
        @ViewBag.message
    </div>

}
else if (ViewBag.status == "Error")
{
    <div class="alert alert-danger">
        @ViewBag.message
    </div>
}